DirectoryPath: "./site/public"
# Hugo's directory structure triggers this:
IgnoreDirectoryMissingTrailingSlash: true
IgnoreAltMissing: true
IgnoreAltEmpty: true
# HTTPHeaders: {"Range": "bytes=0-0", "Accept": "*/*", "User-Agent": "HtmlTest/1.0.0"}
# CheckExternal: false
IgnoreURLs:
- "twitter.com"
# CheckFavicon: false
EnforceHTML5: true
IgnoreExternalBrokenLinks: false
LogLevel: 1
