main:
  - pageRef: lucy
    name: Lucy
    weight: 3
  - pageRef: lucy/position
    name: Position 
    parent: Lucy
  - pageRef: posts
    name: Posts
    weight: 5
  - pageRef: tags
    name: Topics
    parent: Posts
  - pageRef: cruising
    name: Cruising
    weight: 4

